Fix: Multi-Select - Allow unique pills incase of duplicate values
Travelopia/web-components pull request #84
Opened 2024-10-25 04:06 UTC by Takshil-Kunadia

Fixes #71 & partially fixes #26

2025-01-16 20:24 UTC, Souptik2001 approved these changes
Looks good!

2025-01-17 04:20 UTC, sagarjadhav requested changes
@Takshil-Kunadia Added notes.

2025-01-17 04:20 UTC, sagarjadhav commented on src/multi-select/index.html
> +			background-color: gainsboro;
@Takshil-Kunadia `background-color` may create an issue in projects, as we need to overwrite the background color in projects.

2025-01-17 04:20 UTC, sagarjadhav commented on src/multi-select/index.html
> +					<div> Most Popular </div>
@Takshil-Kunadia Please remove the spaces from content.

2025-01-17 05:01 UTC, Takshil-Kunadia commented on src/multi-select/index.html
> +			background-color: gainsboro;
This is added to the example `html file` and not the `style.scss` file, it is just for the demos so it shouldn't affect any styles.

2025-01-17 05:02 UTC, Takshil-Kunadia commented on src/multi-select/index.html
> +					<div> Most Popular </div>
Removed the spaces. ✅

2025-01-17 05:08 UTC, sagarjadhav approved these changes

2025-01-17 05:08 UTC, sagarjadhav commented on src/multi-select/index.html
> +			background-color: gainsboro;
Thanks @Takshil-Kunadia

2025-01-30 21:39 UTC, merged

2025-01-30 21:40 UTC, junaidbhura commented
Thank you @Takshil-Kunadia !